### ISSUE TITLE
Refactor application form backend API to rely solely on POST

### ISSUE THREAD

**Issue by chrislessard** [uoft-tapp/tapp#100]
The current API for the backend provides endpoints for receiving PUT and POST requests. 

Based on how the application form works in the frontend, we would need to introduce unnecessary business logic to the frontend so as to make use of both these endpoints. Instead, we should refactor the backend to drop PUT requests, and have POST handle everything. We should customize the response so that the user has some visibility about whether they have created a new DB record or updated a pre-existing one.

**Comment by siefkenj** [comment]
Done! The behavior now is: if you pass in a valid ID, it will update, otherwise, it will create. All endpoints are GET or POST.
