### ISSUE TITLE
[App] Implement deployment scripts

### ISSUE THREAD

**Issue by dingtaoliu** [uoft-tapp/tapp#101]
Currently the project run in development through two docker containers
    - a container that runs the rails api server 
    - a container that runs webpack-dev-server which serves the react app and enables hot 
      module reloading 

In production, the the frontend will not be served by webpack-dev-server.  Instead, we need build the frontend with webpack, and then serve the javascript bundle and static assets ourself.  There are a few different ways of doing this.  

1) We can serve the frontend with our rails api server, which involves using gems like webpack and rails-react.  This means that we will only need one container to run the app in production, and all requests will hit the api server instead of the react app.  

2) We can serve the frontend with a light node.js server.  This allow us to disentangle the frontend and the backend, however we will need to run two containers/services in production, and setting up the network for the two to communicate through docker could be tricky.  

At this point I am not sure what kind of server we will be deploying the app to.  There are guides online for deploying projects that are similar to TAPP (rails backend and react frontend), but most of them are for Heroku.

**Comment by chrislessard** [comment]
I think it would be best for us to stick with the KISS principle here. As you mentioned, Rails already provides a tried-and-tested infrastructure for this problem that we can (and, imo, should) leverage. It's become more clear to us recently that the decision to divorce the frontend from the back didn't receive as much reflection as it perhaps should have when the decision was made. If we follow option 2, I believe we'll be introducing a rift between the frontend in development and in production that would only lead to developer headache.
