### ISSUE TITLE
[Frontend] ApplicationForm div gets overlapped by footer

### ISSUE THREAD

**Issue by dingtaoliu** [uoft-tapp/tapp#102]
The ApplicationForm component renders a list of question and answer fields in a div, but this div gets overlapped by the footer.  I added a few br tags at the end of the div so that you can't see the overlap, but we should find a proper way of dealing with it.  To reproduce the issue, remove the br tags in the ApplicationForm component and render the page at localhost:8000/application.  

I think we should be wrapping the div in a Grid tag that can be imported from react-bootstrap, you can take a look at how the positions table is rendered for reference.

**Comment by siefkenj** [comment]
Application form is being rewritten, so this issue is stale.
