### ISSUE TITLE
[App] CP initial implementation

### ISSUE THREAD

**Issue by michellemtchai** [uoft-tapp/tapp#103]
This involves creating tables, routes, and UI for contract presentment (CP).

For the table, the following tables was created:
- `assignment`
  - `applicant_id`: foreign key
  - `position_id`: foreign key
  - `hours`: int
  - `pay1`: float
  - `pay2`: float
  - `start_date`: date
  - `end_date`: date
  - `status`: `unsent` (0), `sent` (1), `accepted` (2), `rejected` (3), `withdrawn` (4)
- `offers`
  - `assignment_id`: foreign key
  - `hours`: int
  - `pay1`: float
  - `pay2`: float
  - `start_date`: date
  - `end_date`: date
  - `status`: `unsent` (0), `sent` (1), `accepted` (2), `rejected` (3), `withdrawn` (4)

For the routes, the following routes was created:
- GET `/api/v1/assignments`: returns all assignments
- GET `/api/v1/assignments/{id}`: returns assignment with `id`
- POST `/api/v1/assignment`: create a new assignment with `position_id`, `applicant_id`, `hours`, `pay1`, `pay2`
- PUT `/api/v1/assignment/{assignment_id}`: can modify the attributes in assignment
- GET `/api/v1/offers`: returns all offers
- GET `/api/v1/offers`: returns offer with `id`

For the UI, the design should follow that of the old CP and new ABC view for reference.

**Comment by chrislessard** [comment]
Do we have a more detailed plan or list of to-do's for this ? It would be nice to enumerate them here with links to the relevant issues so that those interested can organize themselves more straightforwardly.

**Comment by michellemtchai** [comment]
Should I move the description I made on the corresponding PR here? A lot of the plans for this portion is still on the planning stage in Slack, so nothing is really concrete as of now.

**Comment by chrislessard** [comment]
Please do. It would be best that we try to keep everything documented via GH issues, as this is the easiest way for everyone to track which work is available and how things are progressing in an organized fashion.

**Comment by michellemtchai** [comment]
I've moved the description over. Does that mean I continue to write in the description here when I work on the PR?

**Comment by chrislessard** [comment]
No, you don't need to do that :) All I was really looking for here was a bit more specificity into what constitutes an "initial implementation", as its not immediately clear. The goal for our commits is to be as upfront as possible about the specific work involved.
