### ISSUE TITLE
does position need two relationships with position_preference ?

### ISSUE THREAD

**Issue by jmzaleski** [uoft-tapp/tapp#137]
https://github.com/uoft-tapp/tapp/blob/726a3ec306f5480267609d4f75fbf4ae0b552876/api/app/models/application.rb#L8

We want position to have a relationship with Applicant THROUGH position_preference.

But why do we want Position to have a second has_many relationship with position_preference??

Apologies in advance if this is some rails modeling foible that I should know.

**Comment by George334456** [comment]
Is this done w/ Michelle's PR?

**Comment by siefkenj** [comment]
Schema has been redone.
