### ISSUE TITLE
[Frontend] Lock ESLint version to 6.1.0

### ISSUE THREAD

**Issue by thezane** [uoft-tapp/tapp#209]
A new issue in ESLint 6.2.0 causes loop variables in for loops to be flagged as defined but never used.  We will restrict our version of ESLint to 6.1.0 until the issue is resolved:
https://github.com/eslint/eslint/issues/12117

**Comment by thezane** [comment]
The ESLint version in root package.json and .travis.yml must be changed back when bugs in ESLint 6.2.0 are resolved.  The yarn.lock must be regenerated.

**Comment by michellemtchai** [comment]
Apparently, `babel-eslint` also has to be locked at `@10.0.2` in order for the Travis tests to pass.

**Comment by siefkenj** [comment]
We're currently locked at `6.1.0`. Its probably safe to upgrade now, but I'm closing this issue.
