### ISSUE TITLE
[Frontend] Redesign application form

### ISSUE THREAD

**Issue by thezane** [uoft-tapp/tapp#222]
The application form at /application should be redesigned to (1) improve its look and (2) allow applicants to provide all info needed by the TA coordinator and HR:

### Structure

**Header labeled "Personal Information"**

_1 - 10 are default inputs or dropdowns and must be filled unless otherwise stated_

1. First name
2. Last name
3. UofT email (include another email if you do not have UofT email)
4. Phone number
5. Student number
6. Address
7. Department: Dropdown with the following options hardcoded:
- Computer Science
- Electrical and Computer Engineering
- Mechanical and Industrial Engineering
- Mathematics
- Statistics
- Faculty of Information
- Insitute of Biomaterials and Biomedical Engineering
- Other (fill in textbox)
8. Program: Dropdown with the following options hardcoded:
- PhD
- MSc
- MASc
- MScAC
- UG
- Postdoc
- MEng
- Other (fill in textbox)
9. Year in program
10. Research area (optional)

_11 - 13 are binary radio inputs and must be filled_

11. Will you be enrolled as UofT graduate student for TA session?
12. If you are an undergraduate student, please respond to the following statement:  I grant permission to the TA coordinator to access my academic history.
- Only show if person selects "No" to 11
13. Have you completed UofT TA training?

**Header labeled "Qualifications"**

_14 - 19 are textboxes and do not have to be filled unless otherwise stated_

14. Teaching experience:
List past relevant TA experience and/or teaching experience in chronological order at UofT and elsewhere. Please provide Appointment Dates, Campus/University, Course Number, and Course Name (approximate) wherever possible.
15. Academic qualifications:
List or describe any relevant degrees, courses taken, or other work experience.
16. Technical skills:
List the programming languages and/or knowledge areas that you are competent or expert in. Someone competent in a programming language might need to consult a reference infrequently when answering questions. Check the qualifications for the courses you are interested in TAing to see which programming languages or knowledge areas apply.
17. Not available:
Indicate any times that you will be unavailable for TA duties. This might include a period of several days when you are away at a conference or for other travel, or it might include weekly commitments such as other employment. Please provide dates (e.g. Oct 15-20) or times (e.g. Mon-Thu 9-5) where known. If no availability issues, write "No conflicts".
18. Other information:
Please provide any other information about yourself that would help us make hiring decisions.
19. Special needs:
Describe any special need issues or other difficulties for this application session.  We will keep this as confidential as possible, but this will be seen by TA administrations and instructors of classes for which you apply.

Upload PDF resume (optional)

Replace "Submit" button with "Save and continue"

### Style
Styling of application form should be done via React Bootstrap only.

**Comment by siefkenj** [comment]
Fixed in #568
