### ISSUE TITLE
Adding an application to a session not working in real API

### ISSUE THREAD

**Issue by colezemel** [uoft-tapp/tapp#334]
Upsert an application working in Mock API but not in the Real API. 

**Example**: When ran through on Swagger with session_id = 1, we get an applicant with id = 1. Adding these values to the API post (upsert an application) gives a success in Mock API but the following error in the Real API: _Validation failed: Applicant must exist_

**Comment by siefkenj** [comment]
Should be working now. We'll reopen if it isn't, but we don't really upload applications at this point.
