### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by siefkenj** [uoft-tapp/tapp#376]
Here's a list of UI issues that needs to be addressed.

- [x] Remove TAPP/CP toggle (it's just TAPP); Make a hierarchical tab structure instead
  - `Admin` (this what is currently called TAPP)
  - Matching
  - Applications and Postings  
- [x] Landing page for `Admin`:
   - If no there is no active session, it is prominently displayed first; if there is an active session, show what session is selected and how to select a different one.
   - Brief descriptions of what the tabs do.
- [x] `Sessions`: Dates formatted in readable way
- [x] `Sessions`: Rates are editable
- [x] Restyle the "Add/Edit" buttons in a consistent way across pages (so they look good from a UI/UX perspective).
- [x] `Contract Templates` Ability to upload new template
- [x] `Contract Templates` Ability to preview template
- [x] `Contract Templates` Ability to download
- [x] `Instructors` "Add Instructor" dialog needs email
- [x] `Instructors` Instructors table needs a delete option
- [x] `Instructors` Instructors page needs an import/export option
- [x] `Positions` Readable dates
- [x] `Positions` Editable fields
- [x] `Positions` A sophisticated view (the spreadsheed doesn't and shouldn't include duties, etc., but we need to be able to see/edit those fields).
- [x] `Positions` Show `total number of hours`, `enrollment`, `waitlist`, and `number of TAs currently assigned`
- [x] `Assignments` Filter doesn't work on status
- [x] `Assignments` UI needs to be rethought (button placement, menus, etc.)
- [x] `Assignments` actions that aren't available should be disabled
- [x] `Assignments` should be able to see if an offer was withdrawn (instructor view)
- [x] `Summary` delete this page
- [x] `Import/Export` interface for instructions, positions, assignments.
- [x] `Applicants` view is missing.
- [x] `Applicants` should only be able to be deleted if they have no assignments
Longer term:
- [ ] Add `Reporting and Statistics` tab

**Comment by wisemandenny** [comment]
@siefkenj 
> Sessions: Rates are editable

Which rate? Do you mean `model/sessions/active_session/rate1` (and `rate2`) or do you mean `model/sessions/_model_data/<array element index>/rate1` and (`rate2`)

**Comment by siefkenj** [comment]
You will never touch `_modelData`. When you make an API call, it is automatically updated to be in sync with the backend. So, you will make API calls for `rate1` and `rate2`.

**Comment by wisemandenny** [comment]
- [x] Make a wrapper for the info/activity areas of each section
- [x] When you change the URL route (e.g. `/tapp/sessions`), the navigation bar should update as well (deep linking)
- [x] Remove the routes which don't exist
- [x] Duplicate session selector under the "there is no active session selected" on the admin landing page
- [x] half as much vertical padding around secondary tabs on navbar
- [x] blue color should mean item is selected, black should mean unselected (currently it is reversed)

**Comment by wisemandenny** [comment]
- [x] first subroute should be selected by default when the page loads for the first time (otherwise no subroute tab is selected and it looks weird)

**Comment by wisemandenny** [comment]
@siefkenj 
> - [x]  `Assignments` Filter doesn't work on status

This seems to work, what about it doesn't work?

I tried typing "pending", "accepted", etc, in the filter field and it worked as intended. I also pivoted the table on "status", and that worked too.

**Comment by wisemandenny** [comment]
@siefkenj @reidka 

>- [x] `Positions` editable fields

Which fields should be editable?

**Comment by siefkenj** [comment]
All `Positions` fields should be editable unless there is an assignment for a given position, in which case, the `position_code` should not be editable.

**Comment by siefkenj** [comment]
Most of these UI issues have been fixed. Closing for now!
