### ISSUE TITLE
Contract template upload

### ISSUE THREAD

**Issue by siefkenj** [uoft-tapp/tapp#387]
An `admin` should have the ability to upload a `contract_template`. The template file name should be sanitized on upload. When this feature is implemented, the `Preview/download a template` test can be updated to never abort.

**Comment by siefkenj** [comment]
See https://github.com/uoft-tapp/tapp/blob/2db515aa719b1349b33a6ef6c64cf2dcc3115abb/frontend/src/tests/template-tests.js#L169 which should be removed when this is done.

**Comment by wisemandenny** [comment]
This works on the MockAPI but not on the real API.
When you upload a contract template on the real API this is the error message from the backend container:
~~~
backend_1      | ERROR: No such file or directory @ realpath_rec - /app/"
backend_1      | Traceback:
backend_1      |        /controllers/api/v1/admin/contract_templates_controller.rb:96:in `realdirpath'
backend_1      |        /controllers/api/v1/admin/contract_templates_controller.rb:96:in `realdirpath'
backend_1      |        /controllers/api/v1/admin/contract_templates_controller.rb:96:in `template_file_full_path'
backend_1      |        /controllers/api/v1/admin/contract_templates_controller.rb:59:in `upload'
~~~

**Comment by siefkenj** [comment]
Strange...it works for me

**Comment by siefkenj** [comment]
We need to test this again and close the issue if it's working.
