### ISSUE TITLE
[Test] import/export functions

### ISSUE THREAD

**Issue by siefkenj** [uoft-tapp/tapp#394]
We need tests for the import/export functions that test importing actual spreadsheets and json files.

**Comment by wisemandenny** [comment]
start with isolated functions, e.g. diff, read, import, export

**Comment by Altair59** [comment]
1. import/export tests need to test once `prepareData` and round trip once
2. test each type of Object's `prepareSpreadsheet` function
3. test each type of Object's `prepareMinimal` function
4. tests on correct Object data and some with strange characters

**Comment by Altair59** [comment]
create 4 PRS:
1. hoist all prepareData functions
2. improve object data and object file
3. import test
4. export test
