### ISSUE TITLE
Usability: Add position

### ISSUE THREAD

**Issue by reidka** [uoft-tapp/tapp#432]
In the add position dialog

- [x] Change "Course Code" to "Position Code"  (We sometimes have more than one position per course.)
- [x] Add a note saying that Start Date and End Date should only be set here to override the Session Start and End Dates
- [x] Change Waitlisted to Waitlist
- [x] Should not be able to enter fields into a Add Position Dialog if a session has not been selected.  Should get an error message first.

**Comment by siefkenj** [comment]
Resolved by #436
