### ISSUE TITLE
[Frontend] the delete position action is not implemented correctly and raises an error when clicked

### ISSUE THREAD

**Issue by dingtaoliu** [uoft-tapp/tapp#57]
In the edit position popup, there is a delete button that allows the user to delete the position.  However, the redux action for this delete is not implemented correctly, and raises an error when clicked.  We need to complete the implementation: 

    - make a request to the rails api to delete the position
        - if the request was successful, pass dispatch a deletePositionSuccess action
        - else, log the error and notify the user

**Comment by chrislessard** [comment]
Solved in https://github.com/uoft-tapp/tapp/pull/60
