### ISSUE TITLE
[Investigation] Modify the frontend dockerfile so that yarn does not need to be reinstalled every rebuild

### ISSUE THREAD

**Issue by dingtaoliu** [uoft-tapp/tapp#58]
Each time the code base is changed, we can either rebuild the docker image or inject the updated code base into the running container.  Currently due to how caching works in docker, because the command that copies the code base into the image comes before the command that installs yarn, if we rebuild after a code base change, all subsequent commands are executed.

**Comment by chrislessard** [comment]
Are you referring to this line ? 

```RUN yarn install```

To be clear, yarn comes preinstalled with the node image that the docker file pulls. `yarn install` is effectively installing all the packages specified in `package.json`. That said, I see where you're coming from, we should handle this. I believe a workaround is detailed here https://hackernoon.com/using-yarn-with-docker-c116ad289d56 

I can investigate further if you'd like.
