### ISSUE TITLE
Getting 500 Error Code Related to Surveyjs Data Submission

### ISSUE THREAD

**Issue by mertkaya1033** [uoft-tapp/tapp#609]
I am receiving internal server errors when I submit an application via the `/public/postings/:url_token/submit` route if:

- [ ] Surveyjs submission body does not include an `answers` prop
- [ ] Posting does not have any positions (i.e. have not added a posting position via the `/admin/postings/:id/posting_positions` route)
- [ ] Positions exist for a posting, but there are position preferences.

**Comment by siefkenj** [comment]
Several of these should have been fixed via #610. Can you verify?
