### ISSUE TITLE
Switch to Github Actions

### ISSUE THREAD

**Issue by siefkenj** [uoft-tapp/tapp#699]
Travis has caused a lot of headaches and stopped testing builds for my projects over the weekend (Feb 6, 2023). I suggest we move to Github actions.

@elaine-huynh Could you look into this? It would be high priority since CI needs to run before merging any future PRs.

**Comment by elaine-huynh** [comment]
I feel we should try figuring out whatever might be up with Travis instead? Site says that there's a negative credit balance when I try to restart a tapp build.

**Comment by siefkenj** [comment]
No, let's switch. I'm tired of Travis.

You can look here for an example of how I converted one of my other repositories https://github.com/siefkenj/unified-latex/tree/main/.github/workflows

**Comment by siefkenj** [comment]
I just added a `build.yml` in `.github/workspaces`. It can be adjusted to do what we need with actions. (Most stuff should carry over from the .travis.yml)
